sprite $backstage [40x51/16] {
FFFFFFFFFFFFFFFFFFFFFFEEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFEEEEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEEEEEEEEFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFEEEEEEEEEEFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFEEEEEEEEEEEEFFFFFFFFF
FFFFFFFFFFFFFFFFFEEEEEEEEEEEEEEEEFFFFFFF
FFFFFFFFFFFFFFFFFEEEEEEFFEEEEEEEEEFFFFFF
FFFFFFFFFFFFFFFEEEEEEEFFFFFEEEEEEEEEFFFF
FFFFFFFFFFFFFFEEEEEEEEFFFFFFDEEEEEEEEFFF
FFFFFFFFFFFFFEEEEEEEEFFFFFFFFFEEEEEEEEFF
FFFFFFFFFFFFFEEEEEEEFFFFFFFFFFFFEEEEEEEF
FFFFFFFFFFFFEEEEEEFFFFFFFFFFFFFFFEEEEEEF
FFFFFFFFFFEEEEEEEEEFFFFFFFFFFFFFFFEEEEEE
FFFFFFFFFFEEEEEEEEEEFFFFFFFFFFFFFFEEEEEE
FFFFFFFFFEEEEEEEEEEEEEFFFFFFFFFFFFEEEEEE
FFFFFFFEEEEEEEEEEEEEEEEFFFFFFFFFFEEEEEEE
FFFFFFFEEEEEEDFFEEEEEEEEFFFFFFFFEEEEEEEF
FFFFFEEEEEEEFFFFFEEEEEEEEEEFFFEEEEEEEEEE
FFFFEEEEEEEFFFFFFFFEEEEEEEEEEEEEEEEEEEFE
FFFEEEEEEEFFFFFFFFFFFEEEEEEEEEEEEEEEFEEE
FFEEEEEEEFFFFFFFFFFFFFEEEEEEEEEEEEEFEEEE
FEEEEEEEFFFFFFFFFFFFFFFFEEEEEEEEFFEEEEEF
EEEEEEEEFFFFFFFFFFFFFFFFEEEEEFEEEEEEEEFE
FEEEEEEEEEFFFFFFFFFFFFFFFEEEEEEEEEEEEFEE
EEFEEEEEEEEEFFFFFFFFFFFFEEEEEEFEEEEEFEEE
EEEFFEEEEEEEEFFFFFFFFFFFEEEEEEFEEEFFEEEF
EEEEEFEEEEEEEEEFFFFFFFFEEEEEEEFFFEEEEEEF
EEEEEEEFEEEEEEEEEFFFFBEEEEEEEFEEEEEEEEEE
DFEEEEEEFEEEEEEEEEEEEEEEEEEEEFEEEEEEEFEE
EEFFEEEEEEFEEEEEEEEEEEEEEEEEEEFEEEEEEEEE
EEEEFEEEEEEEEEEEEEEEEEEEEEFEEEFEEFEEEEEF
EEEEEEEEEEEEEFFEEEEEEEEEEFEEEFDEEEEEEEFE
FEEEEEEEEEEEEEEEFEEEEEEFEEEEEFEEEEEEEFEE
EEFEEEEEEFEEEEEEEEEEEEEEEEEEEEEEEEEEFEEE
EEEFEEEEEEEEEEEEEEEEEEEEEEEFEEFEEEFFEEEF
EEEEEFEEEEEEEEEEEEEEEEEEEEFEEEFFFEEEEEEF
EEEEEEEFEEEEEEFEEEEEEEEEFEEEEFEEEEEEEEFF
FFEEEEEEFEEEEEEEECFFFFEEEEEEFFEEEEEEEFFF
EEFFEEEEEEFEEEEEEEEEEEEEEEEEEEFEEEEFFFFF
EEEEFEEEEEEEEEEEEEEEEEEEEEFEEEFEEFFFFFFF
EEEEEFEEEEEEEFEEEEEEEEEEEEEEEEFFFFFFFFFF
FEEEEEEFEEEEEEEDFEEEEEFFEEEEEFFFFFFFFFFF
FFFEEEEEEFEEEEEEEEEEEEEEEEEEFEFFFFFFFFFF
FFFFEEEEEEEEEEEEEEEEEEEEEEEEEEFFFFFFFFFF
FFFFFEEEEEEEFEEEEEEEEEEEEEEEEEFFFFFFFFFF
FFFFFFFEEEEEEEFEEEEEEEEEFEEEEFFFFFFFFFFF
FFFFFFFFFEEEEEEEEFFFFFDEEEEEEFFFFFFFFFFF
FFFFFFFFFFEEEEEEEEEEEEEEEEEEEFFFFFFFFFFF
FFFFFFFFFFFFEEEEEEEEEEEEEEEFFFFFFFFFFFFF
FFFFFFFFFFFFFEFEEEEEEEEEEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEEEEEEEFFFFFFFFFFFFFFFFF
}

