sprite $eso [51x51/16] {
FFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDFFFFFFFFFFFFFF
FFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDEFFFFFFFFFFFF
FFFFFFFFFFFDDDDDDDDDDDDDDCDDDDDDDDDDDDDDFFFFFFFFFFF
FFFFFFFFFDDDDDDDDDDDDDDD616DDDDDDDDDDDDDDFFFFFFFFFF
FFFFFFFFDDDDDDDDDDDDDDDD101DDDDDDDDDDDDDDDEFFFFFFFF
FFFFFFFDDDDDDDDDDDDDDDDD707DDDDDDDDDDDDDDDDEFFFFFFF
FFFFFFDDDDDDDDDDDDDDDDDDB0CDDDDDDDDDDDDDDDDDDFFFFFF
FFFFFEDDDDDDDDDDDDDDDDDDB0BDDDDDDDDDDDDDDDDDDCFFFFF
FFFFFDDDDDDDDDDDDDDDDDDDB0BDDDDDDDDDDDDDDDDDDDFFFFF
FFFFDDDDDDDDDDDDDDDDDDEEB0BEEDDDDDDDDDDDDDDDDDDFFFF
FFFDDDDDDDDDDDDDDDDDED8310148DEDDDDDDDDDDDDDDDDDFFF
FFFDDDDDDDDDDDDDDDDEB215985413BEDDDDDDDDDDDDDDDDFFF
FFDDDDDDDDDDDDDDDDEB14CEE812941BEDDDDDDDDDDDDDDDDFF
FFDDDDDDDDDDDDDDDDD24DDDDDC51C42DDDDDDDDDDDDDDDDDFF
FDDDDDDDDDDDDDDDDE81CDDDDDED09C08EDDDDDDDDDDDDDDDDF
FDDDDDDDDDDDDDDDDD26EDDDDDDD7BE53DDDDDDDDDDDDDDDDDF
FDDDDDDDDDDDDDDDDC09EDDDDDDDEDE91CDDDDDDDDDDDDDDDDF
CDDDDDDDDDDDDDDEEC2BEEEEEEEEEEEB2DEEDDDDDDDDDDDDDDF
DDDDDDDDDDDDDDD977677777777777776779DDDDDDDDDDDDDDD
DDDDDDDDDDDDDDD112222222222222222211DDDDDDDDDDDDDDD
DDDDDDDDDDDDDDD19EDDDDDDDDDDDDDDDE81DDDDDDDDDDDDDDD
DDDDDDDDDDDDDDD19EDDDDDDDDDDDDDDDE81DDDDDDDDDDDDDDD
DDDDDDDDDDDDDED19EDDDDDDDDDDDDDDDE81DEDDDDDDDDDDDDD
DDDDDDDDDDDDD7919EEEEEEEEEEEEEEEEE8298DDDDDDDDDDDDD
DDDDDDDDDDDDE2619B777777777777777B9253EDDDDDDDDDDDD
DDDDDDDDDDEDC361A547667667667667369253CDEDDDDDDDDDD
DDDDDDDDDE811161A59E87C88C88C78E869261129EDDDDDDDDD
DDDDDDDDEA06B361A58D42B33B23B24D869253B60AEDDDDDDDD
DDDDDDDDE44EE361A58D99B99B99B99D759253EE34EDDDDDDDD
DDDDDDDD4007E361A723333333333333289264E6005DDDDDDDF
FDDDDDE70A80ACC19ECCCCCCCCCCCCCCCE81CCA09A08EDDDDDF
FDDDDDE66EE39ED19EDDDDDDDDDDDDDDDE81DE84EE57EDDDDDF
FDDDDDDDDDDDDDD19EDDDDDDDDDDDDDDDE81DDDDDDDDDDDDDDF
FFDDDDDDDDDDDDD19EEEEEEEEDDEDEEEEE91DDDDDDDDDDDDDFF
FFDDDDDDDDDDDDD1699888889DC668889951DDDDDDDDDDDDDFF
FFFDDDDDDDDDDDD3111111223D9011111114DDDDDDDDDDDDFFF
FFFDDDDDDDDDDDDDDDDDDDDDDDEBBDDDDDDDDDDDDDDDDDDDFFF
FFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFFF
FFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFFFF
FFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFFFF
FFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFFFFF
FFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFFFFFF
FFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFFFFFFF
FFFFFFFFFEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFFFFFFFF
FFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFFFFFFFFFF
FFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDFFFFFFFFFFFF
FFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDEFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFDDDDDDDDDDDFFFFFFFFFFFFFFFFFFFF
}

