sprite $kuberhealthy [51x51/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFAAAAAAAFFFFFFFFFFFFFFAABFFFFFFFFFFFF
FFFFFFFFFFFFFAAAAAAAAAAAFFFFFFFFAAAAAAAAAAFFFFFFFFF
FFFFFFFFFFFAAAAAAAAAAAAAABFFFFAAAAAAAAAAAAAAFFFFFFF
FFFFFFFFFAAAAAAAAEFAAAAAAAAFBAAAAAAAAAAAAAAAABFFFFF
FFFFFFFFBAAAAAFFFFFFFFFAAAAAAAAAAAFFFFFFFAAAAAAFFFF
FFFFFFFBAAAAAFFFFFFFFFFFAAAAAAAAFFFFFFFFFFFAAAAAFFF
FFFFFFFAAAAFFFFFFFFFFFFFFBAAAAFFFFFFFFFFFFFFAAAAFFF
FFFFFFAAAAAFFFFFFFFFFFFFFFBAAFFFFFFFFFFFFFFFFAAAAFF
FFFFFFAAABFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAAAAFF
FFFFFBAAAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAAABF
FFFFFAAAAFFFFFFFFAAFFFFFFFFFFFFFFFFAFFFFFFFFFFAAAAF
FFFFFAAAAFFFFFFFFAABFFFFFFFFFFFFFFAAAFFFFFFFFFFAAAF
FFFFFAAAFFFFFFFFAAAAFFFFFFFFFFFFFFAAAAFFFFFFFFFAAAF
FFFFFAAAFFFFFFFFAAAAFFFFFFFFFFFFFFAAAAFFFFFFFFFAAAF
FFFFFAAAFFFFFFFAAAAACFFFFFFFFFFFFAAAAAAFFFFFFFFAAAF
FFFFFAAAFFFFFFFAAAAAAFFFFFFFFFFFFAAAAAAFFFFFFFFAAAF
FFFFFAAAAFFFFFFAAAAAAFFFAAAAFFFFFAAAAAAAFFFFFFFAAAF
AAAAAAAAAAAAAAAAAAAAAAFAAAAAAFFFAAAAFAAAAAAAAAAAAAF
AAAAAAAAAAAAAAAAAFAAAABAAAAAAAFFAAAAFAAAAAAAAAAAAAF
AAAAAAAAAAAAAAAAAFFAAAAAAAAAAAFFAAAFFFAAAAAAAAAAAFF
FBAAABAAAAAF7AFFFFFAAAAAAFFAAAAAAAAFFFAAAAAAAAAAAFF
FFFFFFFAAAABFFFFFFFCAAAAFFFBAAAAAAAFFFFFFFFFAAAAFFF
FFFFFFFFAAAAAFFFFFFFAAABFFFFAAAAAAFFFFFFFFFAAAAAFFF
FFFFFFFFFAAAAFFFFFFFAAAFFFFFAAAAAAFFFFFFFFAAAAAFFFF
FFFFFFFFFFAAAA7FFFFFBAFFFFFFFAAAAAFFFFFFFAAAAAFFFFF
FFFFFFFFFFFAAAAAFFFFFFFFFFFFFAAAAFFFFFFFAAAAAFFFFFF
FFFFFFFFFFFEAAAABFFFFFFFFFFFFFAAAFFFFFFAAAABFFFFFFF
FFFFFFFFFFFFFAAAAAFFFFFFFFFFFFAAAFFFFFAAAABFFFFFFFF
FFFFFFFFFFFFFFAAAAAFFFFFFFFFFFBAFFFFFAAAAAFFFFFFFFF
FFFFFFFFFFFFFFFAAAAAFFFFFFFFFFFFFFFAAAAAFFFFFFFFFFF
FFFFFFFFFFFFFFFFAAAAAFFFFFFFFFFFFFBAAAAFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFAAAAAFFFFFFFFFFFBAAAAFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFAAAAAFFFFFFFFFBAAAAFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFAAAAAFFFFFFFBAAAAFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFAAAAAFFFFFAAAAAFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFAAAAAFFFBAAAAFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFAAAAAFAAAAAFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFBAAABFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFAAAFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

